apiVersion: example.org/v1alpha1
kind: VyOSClusterFirewall
metadata:
  name: "customer-c-firewall"
  labels:
    customer: "customer-c"
spec:
  clusterName: "cluster01"
  vyosNodes:
    primarynode:
      name: "vyosnode01"
      url: "https://10.7.1.10"  
    secondarynode:
      name: "vyosnode02"
      url: "https://10.7.1.20"
  rules:
  - ruleNumber: 3705
    action: "accept"
    protocol: "tcp"
    destination:
      address: "5.5.7.15"
      port: 80
  - ruleNumber: 3706
    action: "accept"
    protocol: "tcp"
    destination:
      address: "5.5.7.20"
      port: 80
  - ruleNumber: 3707
    action: "accept"
    protocol: "tcp"
    destination:
      address: "5.5.7.10"
      port: 8989

  addToAddressGroup:
    ipAddress: 5.5.7.10
    addressGroups:
    - G-21-TCP
    - G-22-TCP
    - G-80-TCP
    - G-443-TCP
    - G-3389-TCP
    - CLUSTER_ADDRESSES
