apiVersion: example.org/v1alpha1
kind: VyOSClusterStaticRoute
metadata:
  name: "customer-c-staticroute"
  labels:
    customer: "customer-c"
spec:
  clusterName: "cluster01"
  vyosNodes:
    primarynode:
      name: "vyosnode01"
      url: "https://10.7.1.10"
    secondarynode:
      name: "vyosnode02"
      url: "https://10.7.1.20"
  route:
    to: "5.5.7.10/32"
    next-hop-interface: eth3
